stages:
  - setup-env
  - build
  - deploy

variables:
  DOCKER_IMAGE: stay-connected-backend
  DJANGO_APP_PORT: 8000
  APP_HOST: "164.92.200.148"
  APP_DIR: "/root/stay-connected-app/backend"

staging-build-job:
  stage: build
  script:
    - echo "Building Docker Compose on the host..."
    - ssh root@$APP_HOST "mkdir -p $APP_DIR"
    - scp -r * root@$APP_HOST:$APP_DIR
    - ssh root@$APP_HOST "mv $APP_DIR/.env.example $APP_DIR/.env"
    - if [ -f .env ]; then scp .env root@$APP_HOST:$APP_DIR; else echo ".env file not found"; fi
    - ssh root@$APP_HOST "cd $APP_DIR && docker-compose build"

  tags:
    - staging
    - backend

staging-deploy-job:
  stage: deploy
  script:
    - echo "Deploying the Django app on the host..."
    - ssh root@$APP_HOST "cd $APP_DIR && docker-compose down || true"
    - ssh root@$APP_HOST "cd $APP_DIR && docker-compose up -d"
    - echo "Application deployed and running on http://$APP_HOST:$DJANGO_APP_PORT"
  tags:
    - staging
    - backend