  services:
    django:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: stay_connected_django
      # volumes:
      #   - static_files:/home/djangoapp/src/static
      #   - media_files:/home/djangoapp/src/media
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - postgres_db
        - redis


    postgres_db:
      container_name: stay_connected_db
      image: postgres:17.2-bullseye
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      restart: always
      ports:
        - "5432:5432"
      healthcheck:
        test:
          [ "CMD", "pg_isready", "-q", "-d", "stay_connected_db", "-U", "admin" ]
        timeout: 60s
        interval: 10s
        retries: 10

    redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"

      # nginx:
      #   image: nginx:latest
      #   container_name: nginx_reverse_proxy
      #   ports:
      #     - "80:80"
      #   volumes:
      #     - ./nginx:/etc/nginx/conf.d
      #     # - static_files:/home/djangoapp/src/static
      #     # - media_files:/home/djangoapp/src/media
      #   depends_on:
      #     - django
      #   restart: always



  volumes:
    postgres_data:
    # static_files:

