services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stay_connected_django
    volumes:
      - django_static_files:/opt/services/djangoapp/src/static
      - django_media_files:/opt/services/djangoapp/src/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
      - redis
    restart: always
    command: /opt/services/djangoapp/src/start-bash.sh


  postgres_db:
    container_name: stay_connected_db
    image: postgres:17.2-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [ "CMD", "pg_isready", "-q", "-d", "quiz", "-U", "quiz" ]
      timeout: 60s
      interval: 10s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  django_static_files:
  django_media_files: