# Generated by Django 5.1.3 on 2024-12-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_rejected',
        ),
    ]
