# Generated by Django 5.1.3 on 2024-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_answervote_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='vote_type',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike'), (0, 'None')], default=0),
        ),
    ]
