# Generated by Django 5.1.3 on 2024-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_answervote_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='vote_type',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')]),
        ),
    ]
