# Generated by Django 5.1.3 on 2024-12-05 09:09

import authentication.utils
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_score_profile_total_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=authentication.utils.generate_image_path),
        ),
    ]
